<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class ProgramsApplications extends AbstractMigration
{
    public function up(): void
    {
        foreach ([
            "CREATE TABLE IF NOT EXISTS programs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(191) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, summary TEXT NOT NULL, eligibility_summary TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', version INT UNSIGNED NOT NULL DEFAULT 1, created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), INDEX (status), CHECK (status IN ('draft','open','closed','archived'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS cohorts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, program_id BIGINT UNSIGNED NOT NULL, name VARCHAR(180) NOT NULL, starts_on DATE NULL, ends_on DATE NULL, status VARCHAR(20) NOT NULL DEFAULT 'planned', created_at DATETIME(6) NOT NULL, FOREIGN KEY (program_id) REFERENCES programs(id), UNIQUE (program_id, name), CHECK (status IN ('planned','active','completed','archived'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS intakes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, program_id BIGINT UNSIGNED NOT NULL, cohort_id BIGINT UNSIGNED NULL, name VARCHAR(180) NOT NULL, opens_at DATETIME(6) NOT NULL, closes_at DATETIME(6) NOT NULL, seats INT UNSIGNED NULL, eligibility_rules JSON NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, FOREIGN KEY (program_id) REFERENCES programs(id), FOREIGN KEY (cohort_id) REFERENCES cohorts(id), INDEX (status, opens_at, closes_at), CHECK (status IN ('draft','open','closed'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS application_forms (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, intake_id BIGINT UNSIGNED NOT NULL, version INT UNSIGNED NOT NULL, schema_json JSON NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (intake_id) REFERENCES intakes(id), FOREIGN KEY (created_by) REFERENCES users(id), UNIQUE (intake_id, version), CHECK (status IN ('draft','published','retired'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS applications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(32) NOT NULL UNIQUE, intake_id BIGINT UNSIGNED NOT NULL, form_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', answers JSON NOT NULL, eligibility_snapshot JSON NULL, submitted_at DATETIME(6) NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (intake_id) REFERENCES intakes(id), FOREIGN KEY (form_id) REFERENCES application_forms(id), FOREIGN KEY (user_id) REFERENCES users(id), UNIQUE (intake_id, user_id), INDEX (status, submitted_at), INDEX (user_id), CHECK (status IN ('draft','submitted','screening','under_review','shortlisted','waitlisted','request_info','accepted','rejected','withdrawn','enrolled'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS application_documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, application_id BIGINT UNSIGNED NOT NULL, field_key VARCHAR(80) NOT NULL, media_id BIGINT UNSIGNED NOT NULL, uploaded_at DATETIME(6) NOT NULL, FOREIGN KEY (application_id) REFERENCES applications(id), FOREIGN KEY (media_id) REFERENCES media_assets(id), UNIQUE (application_id, field_key)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS application_status_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, application_id BIGINT UNSIGNED NOT NULL, from_status VARCHAR(20) NULL, to_status VARCHAR(20) NOT NULL, actor_id BIGINT UNSIGNED NULL, note VARCHAR(1000) NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (application_id) REFERENCES applications(id), FOREIGN KEY (actor_id) REFERENCES users(id), INDEX (application_id, created_at)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS review_assignments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, application_id BIGINT UNSIGNED NOT NULL, reviewer_id BIGINT UNSIGNED NOT NULL, assigned_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, completed_at DATETIME(6) NULL, FOREIGN KEY (application_id) REFERENCES applications(id), FOREIGN KEY (reviewer_id) REFERENCES users(id), FOREIGN KEY (assigned_by) REFERENCES users(id), UNIQUE (application_id, reviewer_id)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS application_reviews (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, application_id BIGINT UNSIGNED NOT NULL, reviewer_id BIGINT UNSIGNED NOT NULL, score SMALLINT UNSIGNED NOT NULL, internal_notes TEXT NULL, applicant_feedback TEXT NULL, recommendation VARCHAR(20) NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (application_id) REFERENCES applications(id), FOREIGN KEY (reviewer_id) REFERENCES users(id), UNIQUE (application_id, reviewer_id), CHECK (recommendation IN ('shortlist','waitlist','accept','reject'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS cohort_members (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, cohort_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, application_id BIGINT UNSIGNED NULL, status VARCHAR(20) NOT NULL DEFAULT 'enrolled', enrolled_at DATETIME(6) NOT NULL, completed_at DATETIME(6) NULL, FOREIGN KEY (cohort_id) REFERENCES cohorts(id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (application_id) REFERENCES applications(id), UNIQUE (cohort_id, user_id), CHECK (status IN ('enrolled','active','completed','withdrawn'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS participant_profiles (user_id BIGINT UNSIGNED PRIMARY KEY, phone VARCHAR(40) NULL, country VARCHAR(80) NULL, region VARCHAR(80) NULL, birth_year SMALLINT UNSIGNED NULL, gender VARCHAR(40) NULL, alumni_since DATE NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS startups (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180) NOT NULL, sector VARCHAR(80) NULL, summary TEXT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', created_by BIGINT UNSIGNED NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), INDEX (status), CHECK (status IN ('active','archived'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS startup_members (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, startup_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, role VARCHAR(40) NOT NULL DEFAULT 'member', joined_at DATETIME(6) NOT NULL, FOREIGN KEY (startup_id) REFERENCES startups(id), FOREIGN KEY (user_id) REFERENCES users(id), UNIQUE (startup_id, user_id), CHECK (role IN ('founder','co_founder','member'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS milestones (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, startup_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NULL, title VARCHAR(255) NOT NULL, description TEXT NULL, due_on DATE NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', evidence TEXT NULL, evidence_media_id BIGINT UNSIGNED NULL, reviewed_by BIGINT UNSIGNED NULL, reviewed_at DATETIME(6) NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (startup_id) REFERENCES startups(id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (evidence_media_id) REFERENCES media_assets(id), FOREIGN KEY (reviewed_by) REFERENCES users(id), INDEX (status, due_on), CHECK (status IN ('pending','in_progress','submitted','approved','changes_requested','cancelled')), CHECK (startup_id IS NOT NULL OR user_id IS NOT NULL)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS notification_preferences (user_id BIGINT UNSIGNED NOT NULL, scope VARCHAR(60) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, updated_at DATETIME(6) NOT NULL, PRIMARY KEY (user_id, scope), FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB",
        ] as $statement) {
            $this->execute($statement);
        }
    }

    public function down(): void
    {
        throw new RuntimeException('Program and application history cannot be destructively rolled back.');
    }
}
