<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

/**
 * Funding rounds/requests/reviews/approvals/awards/disbursements, impact
 * indicators/targets/results/reports and partner organizations/portal shares.
 * Money is DECIMAL + ISO currency; rule versions are frozen at submission.
 */
final class FundingImpactPartners extends AbstractMigration
{
    public function up(): void
    {
        foreach ([
            "CREATE TABLE IF NOT EXISTS funding_rounds (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(191) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'USD', max_award DECIMAL(15,2) NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', version INT UNSIGNED NOT NULL DEFAULT 1, opens_at DATETIME(6) NOT NULL, closes_at DATETIME(6) NOT NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), INDEX (status, closes_at), CHECK (status IN ('draft','open','closed','archived'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS funding_rule_versions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, round_id BIGINT UNSIGNED NOT NULL, version INT UNSIGNED NOT NULL, weights_json JSON NOT NULL, max_score SMALLINT UNSIGNED NOT NULL DEFAULT 5, created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (round_id) REFERENCES funding_rounds(id), FOREIGN KEY (created_by) REFERENCES users(id), UNIQUE (round_id, version)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS funding_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(32) NOT NULL UNIQUE, round_id BIGINT UNSIGNED NOT NULL, startup_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL, requested_amount DECIMAL(15,2) NOT NULL, currency CHAR(3) NOT NULL, budget_summary TEXT NULL, status VARCHAR(20) NOT NULL DEFAULT 'submitted', rule_version_id BIGINT UNSIGNED NULL, version INT UNSIGNED NOT NULL DEFAULT 1, submitted_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (round_id) REFERENCES funding_rounds(id), FOREIGN KEY (startup_id) REFERENCES startups(id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (rule_version_id) REFERENCES funding_rule_versions(id), INDEX (round_id, status), INDEX (user_id), CHECK (status IN ('submitted','under_review','recommended','approved','rejected','awarded')), CHECK (requested_amount > 0)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS funding_conflicts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, request_id BIGINT UNSIGNED NOT NULL, reviewer_id BIGINT UNSIGNED NOT NULL, declaration VARCHAR(2000) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'declared', cleared_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, cleared_at DATETIME(6) NULL, FOREIGN KEY (request_id) REFERENCES funding_requests(id), FOREIGN KEY (reviewer_id) REFERENCES users(id), FOREIGN KEY (cleared_by) REFERENCES users(id), INDEX (request_id, status), CHECK (status IN ('declared','cleared'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS funding_reviews (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, request_id BIGINT UNSIGNED NOT NULL, reviewer_id BIGINT UNSIGNED NOT NULL, rule_version_id BIGINT UNSIGNED NOT NULL, scores_json JSON NOT NULL, weighted_total DECIMAL(7,3) NOT NULL, recommendation VARCHAR(10) NOT NULL, notes TEXT NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (request_id) REFERENCES funding_requests(id), FOREIGN KEY (reviewer_id) REFERENCES users(id), FOREIGN KEY (rule_version_id) REFERENCES funding_rule_versions(id), UNIQUE (request_id, reviewer_id), CHECK (recommendation IN ('award','decline','hold'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS funding_approvals (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, request_id BIGINT UNSIGNED NOT NULL, approver_id BIGINT UNSIGNED NOT NULL, decision VARCHAR(10) NOT NULL, reason VARCHAR(1000) NULL, rule_version_id BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (request_id) REFERENCES funding_requests(id), FOREIGN KEY (approver_id) REFERENCES users(id), FOREIGN KEY (rule_version_id) REFERENCES funding_rule_versions(id), UNIQUE (request_id), CHECK (decision IN ('approved','rejected'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS awards (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, request_id BIGINT UNSIGNED NOT NULL UNIQUE, amount DECIMAL(15,2) NOT NULL, currency CHAR(3) NOT NULL, conditions TEXT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', awarded_by BIGINT UNSIGNED NULL, awarded_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (request_id) REFERENCES funding_requests(id), FOREIGN KEY (awarded_by) REFERENCES users(id), CHECK (status IN ('active','closed','cancelled')), CHECK (amount > 0)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS disbursements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, award_id BIGINT UNSIGNED NOT NULL, reference VARCHAR(120) NOT NULL UNIQUE, scheduled_on DATE NOT NULL, amount DECIMAL(15,2) NOT NULL, currency CHAR(3) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'planned', authorized_by BIGINT UNSIGNED NULL, authorized_at DATETIME(6) NULL, recorded_by BIGINT UNSIGNED NULL, recorded_at DATETIME(6) NULL, evidence_media_id BIGINT UNSIGNED NULL, note VARCHAR(1000) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (award_id) REFERENCES awards(id), FOREIGN KEY (authorized_by) REFERENCES users(id), FOREIGN KEY (recorded_by) REFERENCES users(id), FOREIGN KEY (evidence_media_id) REFERENCES media_assets(id), INDEX (award_id, status), CHECK (status IN ('planned','authorized','recorded','cancelled')), CHECK (amount > 0)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS impact_indicators (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(60) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, definition TEXT NOT NULL, unit VARCHAR(60) NOT NULL, source VARCHAR(120) NOT NULL DEFAULT 'operational', calculation VARCHAR(255) NOT NULL DEFAULT '', disaggregation JSON NULL, frequency VARCHAR(20) NOT NULL DEFAULT 'annual', owner_user_id BIGINT UNSIGNED NULL, validation TEXT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (owner_user_id) REFERENCES users(id), CHECK (status IN ('active','retired')), CHECK (frequency IN ('monthly','quarterly','annual'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS impact_targets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, indicator_id BIGINT UNSIGNED NOT NULL, period VARCHAR(7) NOT NULL, program_id BIGINT UNSIGNED NULL, target DECIMAL(18,4) NOT NULL, set_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (indicator_id) REFERENCES impact_indicators(id), FOREIGN KEY (program_id) REFERENCES programs(id), FOREIGN KEY (set_by) REFERENCES users(id), UNIQUE (indicator_id, period, program_id)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS impact_results (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, dedupe_key CHAR(64) NOT NULL UNIQUE, indicator_id BIGINT UNSIGNED NOT NULL, period VARCHAR(7) NOT NULL, program_id BIGINT UNSIGNED NULL, cohort_id BIGINT UNSIGNED NULL, geography VARCHAR(120) NULL, value DECIMAL(18,4) NOT NULL, disaggregation JSON NULL, source_note TEXT NULL, evidence_media_id BIGINT UNSIGNED NULL, submitted_by BIGINT UNSIGNED NULL, status VARCHAR(20) NOT NULL DEFAULT 'submitted', verified_by BIGINT UNSIGNED NULL, verified_at DATETIME(6) NULL, published_by BIGINT UNSIGNED NULL, published_at DATETIME(6) NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (indicator_id) REFERENCES impact_indicators(id), FOREIGN KEY (program_id) REFERENCES programs(id), FOREIGN KEY (cohort_id) REFERENCES cohorts(id), FOREIGN KEY (evidence_media_id) REFERENCES media_assets(id), FOREIGN KEY (submitted_by) REFERENCES users(id), FOREIGN KEY (verified_by) REFERENCES users(id), FOREIGN KEY (published_by) REFERENCES users(id), INDEX (status, period), CHECK (status IN ('submitted','verified','published','rejected'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS impact_reports (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, period VARCHAR(7) NOT NULL, summary TEXT NOT NULL, body TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', version INT UNSIGNED NOT NULL DEFAULT 1, created_by BIGINT UNSIGNED NULL, approved_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), FOREIGN KEY (approved_by) REFERENCES users(id), CHECK (status IN ('draft','approved','published'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS partner_organizations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(200) NOT NULL, org_type VARCHAR(20) NOT NULL DEFAULT 'partner', website VARCHAR(255) NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), INDEX (status), CHECK (org_type IN ('donor','partner','sponsor','other')), CHECK (status IN ('active','inactive'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS partner_memberships (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, org_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, member_role VARCHAR(20) NOT NULL DEFAULT 'viewer', status VARCHAR(20) NOT NULL DEFAULT 'active', invited_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, activated_at DATETIME(6) NULL, FOREIGN KEY (org_id) REFERENCES partner_organizations(id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (invited_by) REFERENCES users(id), UNIQUE (org_id, user_id), CHECK (member_role IN ('admin','viewer')), CHECK (status IN ('invited','active','suspended'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS partner_proposals (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, org_id BIGINT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL, summary TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', version INT UNSIGNED NOT NULL DEFAULT 1, created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (org_id) REFERENCES partner_organizations(id), FOREIGN KEY (created_by) REFERENCES users(id), INDEX (org_id, status), CHECK (status IN ('draft','submitted','under_review','committed','declined','withdrawn'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS partner_commitments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, org_id BIGINT UNSIGNED NOT NULL, proposal_id BIGINT UNSIGNED NULL, amount DECIMAL(15,2) NOT NULL, currency CHAR(3) NOT NULL, committed_on DATE NOT NULL, conditions TEXT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pledged', recorded_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (org_id) REFERENCES partner_organizations(id), FOREIGN KEY (proposal_id) REFERENCES partner_proposals(id), FOREIGN KEY (recorded_by) REFERENCES users(id), CHECK (status IN ('pledged','partial','fulfilled','cancelled')), CHECK (amount > 0)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS partner_received (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, commitment_id BIGINT UNSIGNED NOT NULL, reference VARCHAR(120) NOT NULL UNIQUE, amount DECIMAL(15,2) NOT NULL, currency CHAR(3) NOT NULL, received_on DATE NOT NULL, evidence_media_id BIGINT UNSIGNED NULL, recorded_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (commitment_id) REFERENCES partner_commitments(id), FOREIGN KEY (evidence_media_id) REFERENCES media_assets(id), FOREIGN KEY (recorded_by) REFERENCES users(id), CHECK (amount > 0)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS partner_shares (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, org_id BIGINT UNSIGNED NOT NULL, resource_type VARCHAR(20) NOT NULL, resource_id BIGINT UNSIGNED NOT NULL, shared_by BIGINT UNSIGNED NULL, shared_at DATETIME(6) NOT NULL, revoked_at DATETIME(6) NULL, FOREIGN KEY (org_id) REFERENCES partner_organizations(id), FOREIGN KEY (shared_by) REFERENCES users(id), UNIQUE (org_id, resource_type, resource_id), INDEX (org_id, resource_type), CHECK (resource_type IN ('report','document','project'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS partner_access_log (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, org_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, action VARCHAR(10) NOT NULL, resource_type VARCHAR(20) NOT NULL, resource_id BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (org_id) REFERENCES partner_organizations(id), FOREIGN KEY (user_id) REFERENCES users(id), INDEX (org_id, created_at), CHECK (action IN ('view','download'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS partner_notes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, org_id BIGINT UNSIGNED NOT NULL, note TEXT NOT NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (org_id) REFERENCES partner_organizations(id), FOREIGN KEY (created_by) REFERENCES users(id)) ENGINE=InnoDB",
        ] as $statement) {
            $this->execute($statement);
        }
    }

    public function down(): void
    {
        throw new RuntimeException('Funding, impact and partner history cannot be destructively rolled back.');
    }
}
