<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class LearningMentoringCommunity extends AbstractMigration
{
    public function up(): void
    {
        foreach ([
            "CREATE TABLE IF NOT EXISTS courses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(191) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, summary TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', version INT UNSIGNED NOT NULL DEFAULT 1, created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), INDEX (status), CHECK (status IN ('draft','published','archived'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS course_lessons (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, course_id BIGINT UNSIGNED NOT NULL, position INT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NULL, external_url VARCHAR(500) NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (course_id) REFERENCES courses(id), UNIQUE (course_id, position)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS course_enrollments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, course_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, cohort_id BIGINT UNSIGNED NULL, status VARCHAR(20) NOT NULL DEFAULT 'enrolled', enrolled_at DATETIME(6) NOT NULL, completed_at DATETIME(6) NULL, FOREIGN KEY (course_id) REFERENCES courses(id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (cohort_id) REFERENCES cohorts(id), UNIQUE (course_id, user_id), INDEX (user_id), CHECK (status IN ('enrolled','completed','withdrawn'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS lesson_progress (lesson_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, completed_at DATETIME(6) NOT NULL, PRIMARY KEY (lesson_id, user_id), FOREIGN KEY (lesson_id) REFERENCES course_lessons(id), FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS course_sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, course_id BIGINT UNSIGNED NOT NULL, session_at DATETIME(6) NOT NULL, label VARCHAR(180) NOT NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (course_id) REFERENCES courses(id)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS attendance_records (session_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, status VARCHAR(20) NOT NULL, recorded_by BIGINT UNSIGNED NULL, recorded_at DATETIME(6) NOT NULL, PRIMARY KEY (session_id, user_id), FOREIGN KEY (session_id) REFERENCES course_sessions(id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (recorded_by) REFERENCES users(id), CHECK (status IN ('present','absent','excused'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS mentor_profiles (user_id BIGINT UNSIGNED PRIMARY KEY, expertise TEXT NOT NULL, sectors VARCHAR(500) NOT NULL DEFAULT '', availability_notes VARCHAR(1000) NOT NULL DEFAULT '', capacity SMALLINT UNSIGNED NOT NULL DEFAULT 3, discoverable BOOLEAN NOT NULL DEFAULT TRUE, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS mentor_matches (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, mentor_id BIGINT UNSIGNED NOT NULL, participant_id BIGINT UNSIGNED NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'proposed', proposed_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, decided_at DATETIME(6) NULL, FOREIGN KEY (mentor_id) REFERENCES users(id), FOREIGN KEY (participant_id) REFERENCES users(id), FOREIGN KEY (proposed_by) REFERENCES users(id), INDEX (status), CHECK (status IN ('proposed','accepted','declined','ended'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS mentor_sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, match_id BIGINT UNSIGNED NOT NULL, scheduled_at DATETIME(6) NOT NULL, duration_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 60, agenda TEXT NULL, meeting_link VARCHAR(500) NULL, status VARCHAR(20) NOT NULL DEFAULT 'scheduled', outcome TEXT NULL, notes TEXT NULL, notes_visibility VARCHAR(10) NOT NULL DEFAULT 'private', created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (match_id) REFERENCES mentor_matches(id), FOREIGN KEY (created_by) REFERENCES users(id), INDEX (scheduled_at), CHECK (status IN ('scheduled','completed','cancelled')), CHECK (notes_visibility IN ('private','shared'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(191) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, location VARCHAR(255) NOT NULL DEFAULT '', starts_at DATETIME(6) NOT NULL, ends_at DATETIME(6) NULL, capacity INT UNSIGNED NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', version INT UNSIGNED NOT NULL DEFAULT 1, created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), INDEX (status, starts_at), CHECK (status IN ('draft','published','cancelled'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS event_registrations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'registered', created_at DATETIME(6) NOT NULL, FOREIGN KEY (event_id) REFERENCES events(id), FOREIGN KEY (user_id) REFERENCES users(id), UNIQUE (event_id, user_id), CHECK (status IN ('registered','cancelled'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS opportunities (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, category VARCHAR(60) NOT NULL DEFAULT 'general', summary TEXT NOT NULL, details TEXT NULL, deadline DATE NULL, status VARCHAR(20) NOT NULL DEFAULT 'open', created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), INDEX (status, deadline), CHECK (status IN ('open','closed'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS member_profiles (user_id BIGINT UNSIGNED PRIMARY KEY, display_name VARCHAR(120) NOT NULL, bio TEXT NULL, sector VARCHAR(80) NULL, location VARCHAR(120) NULL, discoverable BOOLEAN NOT NULL DEFAULT FALSE, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS community_groups (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(191) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, description TEXT NULL, sector VARCHAR(80) NULL, visibility VARCHAR(10) NOT NULL DEFAULT 'public', created_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY (created_by) REFERENCES users(id), INDEX (visibility), CHECK (visibility IN ('public','private'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS group_members (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, group_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'member', status VARCHAR(20) NOT NULL DEFAULT 'active', created_at DATETIME(6) NOT NULL, FOREIGN KEY (group_id) REFERENCES community_groups(id), FOREIGN KEY (user_id) REFERENCES users(id), UNIQUE (group_id, user_id), INDEX (status), CHECK (role IN ('member','moderator')), CHECK (status IN ('pending','active','left','rejected'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS community_posts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, group_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'visible', created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, FOREIGN KEY (group_id) REFERENCES community_groups(id), FOREIGN KEY (user_id) REFERENCES users(id), INDEX (status, created_at), CHECK (status IN ('visible','hidden','removed'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS community_comments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, post_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, body TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'visible', created_at DATETIME(6) NOT NULL, FOREIGN KEY (post_id) REFERENCES community_posts(id), FOREIGN KEY (user_id) REFERENCES users(id), INDEX (post_id, status), CHECK (status IN ('visible','hidden','removed'))) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS bookmarks (user_id BIGINT UNSIGNED NOT NULL, post_id BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY (user_id, post_id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (post_id) REFERENCES community_posts(id)) ENGINE=InnoDB",
            "CREATE TABLE IF NOT EXISTS moderation_reports (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, target_type VARCHAR(10) NOT NULL, target_id BIGINT UNSIGNED NOT NULL, reporter_id BIGINT UNSIGNED NOT NULL, reason VARCHAR(1000) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'open', resolved_by BIGINT UNSIGNED NULL, resolution_note VARCHAR(1000) NULL, created_at DATETIME(6) NOT NULL, resolved_at DATETIME(6) NULL, FOREIGN KEY (reporter_id) REFERENCES users(id), FOREIGN KEY (resolved_by) REFERENCES users(id), INDEX (status), CHECK (target_type IN ('post','comment')), CHECK (status IN ('open','actioned','dismissed'))) ENGINE=InnoDB",
        ] as $statement) {
            $this->execute($statement);
        }
    }

    public function down(): void
    {
        throw new RuntimeException('Learning, mentoring and community records cannot be destructively rolled back.');
    }
}
